# -*- coding: utf-8 -*-
"""DL prac3 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YvhvBlkxAeX2Q9vsw6dAuJcM3Ze9KWBU
"""

from google.colab import files
uploaded=files.upload()
#above code will be use for uploading data file
import io
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
import numpy as np
#adding data file for use
df = pd.read_csv(io.BytesIO(uploaded['customer data.csv']))
#printing data
print(df)
#naming values of data as properties 
properties = list(df.columns.values)
properties.remove('Exited')
X = df[properties]
y = df['Exited']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
#dividing work into input layer, hidden layer and output layer and will assign activation function to it 
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(7,)),
    keras.layers.Dense(5, activation=tf.nn.relu),
	keras.layers.Dense(5, activation=tf.nn.relu),
    keras.layers.Dense(1, activation=tf.nn.sigmoid),
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, y_train, epochs=20, batch_size=1)

test_loss, test_acc = model.evaluate(X_test, y_test)
print('Test accuracy:', test_acc)